// Generated by https://quicktype.io

export interface ResultAcciones {
    ok:       boolean;
    msg:      string;
    acciones: Accione[];
}

export interface Accione {
    id:     number;
    nombre: string;
    estado: number;
}
