// Generated by https://quicktype.io

export interface ResultAreas {
    ok:   boolean;
    msg:  string;
    area: Area[];
}

export interface Area {
    id:          number;
    nombre:      string;
    abreviatura: string;
    estado:      number;
}
