// Generated by https://quicktype.io

export interface ResultDerivacionInternas {
    ok:         boolean;
    msg:        string;
    derivacion: Derivacion[];
}
export interface ResultDerivacionInterna {
    ok:         boolean;
    msg:        string;
    derivacion: Derivacion;
}

export interface Derivacion {
    id:               number;
    observacion:      string;
    estado_recepcion: number;
    id_accion:        number;
    codigo_tramite:   string;
    id_area:          number;
    id_respuesta:     null;
    TramiteInterno:   TramiteInterno;
}

export interface TramiteInterno {
    codigo_documento: string;
    asunto:           string;
    observacion:      string;
    registrado:       string;
    hora:             string;
    fecha:            string;
    ano:              string;
    folio:            string;
    id_prioridad?:     number;
    id_area:          number;
}
