// Generated by https://quicktype.io

export interface ResultRespuestas {
    ok:        boolean;
    msg:       string;
    respuesta: Respuesta[];
}
export interface ResultRespuesta {
    ok:        boolean;
    msg:       string;
    respuesta: Respuesta;
}

export interface Respuesta {
    id:     number;
    nombre: string;
    estado: number;
}
