// Generated by https://quicktype.io

export interface ResultRutaInternas {
    ok:          boolean;
    msg:         string;
    rutaInterna: RutaInterna[];
}
export interface ResultRutaInterna {
    ok:          boolean;
    msg:         string;
    rutaInterna: RutaInterna;
    area:        Area[];
}


export interface RutaInterna {
    id:             number;
    codigo_tramite: string;
    cantidad:       number;
    id_destino:     string;
    derivacion:     number;
    estado:         number;
    TramiteInterno: TramiteInterno;
}

export interface TramiteInterno {
    codigo_documento: string;
    asunto:           string;
    observacion:      null;
    registrado:       string;
    hora:             string;
    fecha:            string;
    ano:              string;
    folio:            string;
    id_prioridad:     number;
    id_area:          number;
}

export interface Area {
    id:     number;
    nombre: string;
}

