// Generated by https://quicktype.io

export interface ResultRutaExternas {
    ok:          boolean;
    msg:         string;
    rutaExterna: RutaExterna[];
}
export interface ResultRutaExterna {
    ok:          boolean;
    msg:         string;
    rutaExterna: RutaExterna;
    area:        Area[];
}


export interface RutaExterna {
    id:             number;
    codigo_tramite: string;
    cantidad:       number;
    id_destino:     string;
    derivacion:     number;
    estado:         number;
    TramiteExterno: TramiteExterno;
}

export interface TramiteExterno {
    codigo_documento: string;
    proveido:         number;
    asunto:           string;
    observacion:      null;
    registrado:       string;
    hora:             string;
    fecha:            string;
    ano:              string;
    folio:            string;
    id_prioridad:     number;
    id_area:          number;
}

export interface Area {
    id:     number;
    nombre: string;
}
