// Generated by https://quicktype.io

export interface ResultSeguimientos {
    ok:          boolean;
    msg:         string;
    seguimiento: SeguimientoInterno[];
}

export interface SeguimientoInterno {
    id:                number;
    id_derivacion:     number;
    fecha_derivacion:  string;
    hora_derivacion:   string;
    fecha_recepcion:   null;
    hora_recepcion:    null;
    DerivacionInterna: DerivacionInterna;
}

export interface DerivacionInterna {
    id:               number;
    observacion:      string;
    estado_recepcion: number;
    id_accion:        number;
    codigo_tramite:   string;
    id_area:          number;
    id_respuesta:     null;
    Area:             Area;
    Respuestum?:       Respuesta;
}

export interface Area {
    id:          number;
    nombre:      string;
    abreviatura: string;
    estado:      number;
}
export interface Respuesta{
    id:          number;
    nombre:      string;
    estado:      number;
}
