// Generated by https://quicktype.io

export interface ResultTipoDocumento {
    ok:      boolean;
    msg:     string;
    tipoDoc: TipoDoc[];
}

export interface TipoDoc {
    id:     number;
    nombre: string;
    estado: number;
}
