// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface ResultTramiteExternos {
    ok:             boolean;
    msg:            string;
    tramiteExterno: TramiteExterno[];
}

export interface TramiteExterno {
    codigo_documento: string;
    tipo_documento:   number;
    nom_documento:    string;
    asunto:           string;
    observacion:      string;
    registrado:       string;
    hora:             string;
    fecha:            string;
    ano:              string;
    folio:            string;
    id_prioridad:     number;
    id_area:          number;
    proveido:         string;
    TipoDocumento:    TipoDocumento;
}

export interface TipoDocumento {
    id:     number;
    nombre: string;
    estado: number;
}

export interface ResultTramiteExterno {
    ok:             boolean;
    msg:            string;
    tramiteExterno: TramiteExterno;
}