// Generated by https://quicktype.io

export interface ResultTramiteExternos {
    ok:             boolean;
    msg:            string;
    tramiteExterno: TramiteExterno[];
}
export interface ResultTramiteExterno {
    ok:             boolean;
    msg:            string;
    tramiteExterno: TramiteExterno;
}

export interface TramiteExterno {
    codigo_documento: string;
    ciudadano:        string;
    dni:              string;
    asunto:           string;
    proveido:         number;
    observacion:      null;
    registrado:       string;
    hora:             string;
    fecha:            string;
    ano:              string;
    folio:            string;
    id_prioridad:     number;
    id_area:          number;
}
