// Generated by https://quicktype.io

export interface ResultValidarSunat {
  ok:    boolean;
  msg:   string;
  datos: Datos;
}

export interface Datos {
  nombre:   string;
  apellido: string;
  dni:      number;
}
